### ISSUE TITLE
name 'List' is not defined

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#10]
------------------------------ Redundant Connection/redundant.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Redundant Connection/redundant.py", line 29, in <module>
    class Solution:
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Redundant Connection/redundant.py", line 30, in Solution
    def findRedundantConnection(self, edges: List[List[int]]) -> List[int]:
NameError: name 'List' is not defined

**Comment by aurimas13** [comment]
Fixed it. Should work
