### ISSUE TITLE
name 'heapq' is not defined

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#17]
------------------------------ Find the Kth Smallest Sum of a Matrix With Sorted Rows/find.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Find the Kth Smallest Sum of a Matrix With Sorted Rows/find.py", line 35, in <module>
    print(sol.kthSmallest(mat, k))  # Expected output: 7
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Find the Kth Smallest Sum of a Matrix With Sorted Rows/find.py", line 13, in kthSmallest
    current_sum, state = heapq.heappop(heap)
NameError: name 'heapq' is not defined

**Comment by aurimas13** [comment]
Fixed it. Should work.
