### ISSUE TITLE
name 'TreeNode' is not defined

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#20]
------------------------------ Binary Search Tree Iterator/binary.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Binary Search Tree Iterator/binary.py", line 1, in <module>
    class BSTIterator:
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Binary Search Tree Iterator/binary.py", line 3, in BSTIterator
    def __init__(self, root: TreeNode):
NameError: name 'TreeNode' is not defined

**Comment by aurimas13** [comment]
Fixed it. Should work.
