### ISSUE TITLE
Test case 2 failed: expected 8, got 7

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#25]
------------------------------ Last Moment Before All Ants Fall Out of a Plank/last.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Last Moment Before All Ants Fall Out of a Plank/last.py", line 35, in <module>
    run_tests()
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Last Moment Before All Ants Fall Out of a Plank/last.py", line 30, in run_tests
    assert result == expected, f"Test case {i} failed: expected {expected}, got {result}"
AssertionError: Test case 2 failed: expected 8, got 7

**Comment by aurimas13** [comment]
Fixed it. Should work.
