### ISSUE TITLE
'list' object has no attribute 'val'

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#27]
------------------------------ Add Two Numbers/add.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Add Two Numbers/add.py", line 29, in <module>
    Solve = Instant.addTwoNumbers([2,4,3], [5,6,4])  #  "aabb" -> ['baab', 'abba']
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Add Two Numbers/add.py", line 9, in addTwoNumbers
    root = ListNode((l1.val + l2.val) % 10)
AttributeError: 'list' object has no attribute 'val'

**Comment by aurimas13** [comment]
Fixed it. Should work.
