### ISSUE TITLE
TypeError: object of type 'Solution' has no len()

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#28]
------------------------------ Substring with Concatenation of All Words/substring.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Substring with Concatenation of All Words/substring.py", line 60, in <module>
    test_solution(s, words, expected)
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Substring with Concatenation of All Words/substring.py", line 53, in test_solution
    result = s.findSubstring(s, words)
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Substring with Concatenation of All Words/substring.py", line 46, in findSubstring
    return find_all_concatenated_words(s, words)
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Substring with Concatenation of All Words/substring.py", line 14, in find_all_concatenated_words
    if len(s) < total_length:
TypeError: object of type 'Solution' has no len()

**Comment by aurimas13** [comment]
Thank you. Fixed it. Should work.
