### ISSUE TITLE
name 'isBadVersion' is not defined

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#35]
------------------------------ First Bad Version/first.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/First Bad Version/first.py", line 22, in <module>
    Solve = Sol.firstBadVersion(n = 5)  # n = 5, bad = 4 -> 4
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/First Bad Version/first.py", line 8, in firstBadVersion
    if isBadVersion(v):
NameError: name 'isBadVersion' is not defined

**Comment by aurimas13** [comment]
Fixed it. Should work.
