### ISSUE TITLE
'>' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#36]
------------------------------ Count Numbers with Unique Digits/count.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Count Numbers with Unique Digits/count.py", line 22, in <module>
    Solve = Sol.countNumbersWithUniqueDigits([5,2,6,1])
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Count Numbers with Unique Digits/count.py", line 6, in countNumbersWithUniqueDigits
    if n > 10:
TypeError: '>' not supported between instances of 'list' and 'int'

**Comment by aurimas13** [comment]
Fixed it. Should work.
