### ISSUE TITLE
name 'List' is not defined

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#38]
------------------------------ Count Number of Distinct Integers After Reverse Operations/count.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Count Number of Distinct Integers After Reverse Operations/count.py", line 1, in <module>
    class Solution:
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Count Number of Distinct Integers After Reverse Operations/count.py", line 2, in Solution
    def countDistinctIntegers(self, nums: List[int]) -> int:
NameError: name 'List' is not defined

**Comment by aurimas13** [comment]
Thanks. Fixed it. Should work.
