### ISSUE TITLE
name 'lru_cache' is not defined

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#9]
------------------------------ Shortest Palindrome/shortest.py
Traceback (most recent call last):
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Shortest Palindrome/shortest.py", line 27, in <module>
    Solve = Instant.minDistance(word1="intention", word2="execution")  # word1 = "intention", word2 = "execution" -> 5
  File "/Users/hughbrown/workspace/Solutions-To-Problems/LeetCode/Python Solutions/Shortest Palindrome/shortest.py", line 4, in minDistance
    @lru_cache(maxsize=None)
NameError: name 'lru_cache' is not defined

**Comment by aurimas13** [comment]
Fixed it. Should work.
